### ISSUE TITLE
Error running fix mode

### ISSUE THREAD

**Issue by NArnott** [benmccallum/dotnet-fix-references#3]
I follow the steps as outlined. I end up with a flat root source folder with one sln file and several csproj files. However, when I run **dotnet references fix** I get the following error, which seems to originate from dotnet itself. Any ideas how to fix?

> Step 15/25 : RUN dotnet references fix -ep MySolution.sln -wd . -rupf
 ---> Running in b13ea6e2a0a9
Specify which project file to use because this '/src' contains more than one project file.
The command '/bin/sh -c dotnet references fix -ep MySolution.sln -wd . -rupf' returned a non-zero code: 1

Here's my dockerfile build phase that results in the error:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

#Set up dotnet tools
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install -g dotnet-references

WORKDIR /src
COPY *.sln ./
COPY */*.csproj ./
RUN dotnet references fix -ep MySolution.sln -wd . -rupf
```

**Comment by benmccallum** [comment]
Hi @NArnott, I've indeed seen this before and it's a limitation of the dotnet cli from memory. Are you able to have a quick google for that error, I'm sure you'll find the issue on the dotnet core repo. If you can post your list of files when you run the CMD too that might help us figure out what the circumstance is!

**Comment by NArnott** [comment]
At this point, there is a single sln file, and 6 csproj files in the /src folder. That's all that was copied to the container at that point. It seems like the dotnet executable just doesn't like having multiple sln/proj files in the same folder, which is what I was hoping this tool would fix due to docker's COPY limitations.

I'm wondering if it's only an issue with the 3.x (3.1) dotnet tools? Have you tested using that version?

**Comment by benmccallum** [comment]
I'm using this on 2.2 and 3.1 builds at the moment, but I think you're suspicions are correct because I've got my .sln file one level down in a subfolder by itself as it so happens. 

Here's the dotnet cli issue: https://github.com/dotnet/sdk/issues/7226

The problem is the .sln file needs to be in the correct relative path to start with so that the rest of the .csproj files moves into their correct place too, but I think the issue is caused by the cwd when you execute the `dotnet` cmd, so potentially if you just create a directory like `./temp`, set that as your CWD and then use the arguments to point to the rights files, all might be good in the world.

```
WORKDIR /src
COPY *.sln ./
COPY */*.csproj ./

# Make and go to a temp directory to execute the tool from
RUN mkdir temp # or equivalent linux cmd
WORKDIR temp

# Refer to sln file and working directory with ..
RUN dotnet references fix -ep ../MySolution.sln -wd .. -rupf
```

Can you give that a try and let me know how you go? If it's all good, I'll update the docs. Bit painful this one :P

**Comment by NArnott** [comment]
Didn't seem to work using `WORKDIR temp`, but a slight tweak of your idea works for me:

```
WORKDIR /src/temp 
RUN dotnet references fix -ep ../MySolution.sln -wd .. -rupf
WORKDIR /src
```

Thanks for you help

**Comment by benmccallum** [comment]
Ah yep, I guess you weren't already in the /src directory. My example started with a WORKDIR /src.

Cool, I'll update the docs. Glad we could find a workaround!
